const LANGS = [
  { id: "en", short: "EN", label: "English", intl: "en-GB" },
  { id: "da", short: "DA", label: "Dansk", intl: "da-DK" },
  { id: "de", short: "DE", label: "Deutsch", intl: "de-DE" },
  { id: "nl", short: "NL", label: "Nederlands", intl: "nl-NL" },
];

const catalogs = {
  en: {
    nav: { home: "Home", dashboard: "Dashboard", cases: "Cases", naw: "Registry", persons: "Persons", companies: "Companies", admin: "Administrator", employees: "Employees", audit: "Audit log", settings: "Settings", newCase: "+ New case", newEmployee: "+ New employee", signOut: "Sign out", search: "Search persons, companies" },
    search: { placeholder: "Search persons, companies, cases…", nothing: "Nothing found" },
    login: { title: "Sign in", email: "Email", password: "Password", continue: "Continue", demo: "Demo", error: "Incorrect email or password.", microsoft: "Sign in with Microsoft", orEmail: "or sign in with email" },
    onboard: { title: "Welcome", lede: "A few steps to get this workspace ready.", stepOf: "Step {n} of {total}", org: "Organisation", orgLede: "Application name and how case numbers are built.", profile: "Profile", profileLede: "Choose whether this workspace is a case system, an HR system, or both.", profileCases: "Case management", profileCasesHint: "Cases, persons and companies. Employees stay system users.", profileHr: "HR", profileHrHint: "Keep employee records, contracts and HR documents.", profileBoth: "Cases and HR", profileBothHint: "Case management plus an employee register.", personeelPrefix: "Personnel number prefix", admin: "Administrator", adminLede: "This account can manage settings, users and integrations.", create: "Create", createLede: "Connect OmniDocs Create to generate documents. You can skip this and set it up later under Settings.", azure: "Microsoft Entra ID", azureLede: "Optional sign-in with work accounts. You can skip this and set it up later under Settings.", next: "Continue", skip: "Skip for now", finish: "Finish setup", back: "Back", passwordConfirm: "Confirm password" },
    azure: { title: "Microsoft Entra ID", lede: "Let employees sign in with their Microsoft work account.", tenantId: "Tenant ID", clientId: "Application (client) ID", clientSecret: "Client secret", keepSecret: "leave empty to keep", redirectUri: "Redirect URI", redirectHint: "Register this URI as a Web redirect in the Entra app registration.", save: "Save connection", clientConfigured: "App registered", clientMissing: "App missing" },
    dash: { title: "Dashboard", lede: "Overview of cases, documents, and your core registry.", hrLede: "Overview of employees and documents.", total: "Total cases", open: "Open", progress: "In progress", closed: "Closed", split: "Split by status", waiting: "Waiting", overdue: "Lead time exceeded", noOverdue: "No overdue cases.", overdueBadge: "Overdue", viewAll: "View all cases", recentCases: "Recent cases", noCases: "No cases yet.", recentDocs: "Recent documents", noDocs: "No documents uploaded yet.", board: "Board", recentEmployees: "Recent employees", noEmployees: "No employees yet.", viewEmployees: "View all employees" },
    status: { nieuw: "New", in_behandeling: "In progress", wacht_op_info: "Waiting", afgerond: "Closed", geannuleerd: "Cancelled" },
    priority: { laag: "Low", normaal: "Normal", hoog: "High", urgent: "Urgent" },
    role: { admin: "Administrator", zaakmanager: "Case manager", medewerker: "Employee" },
    group: { open: "Open", progress: "In progress", closed: "Closed" },
    personGroup: { active: "Active", anon: "Anonymised" },
    companyGroup: { linked: "With cases", idle: "No cases" },
    common: { save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", apply: "Apply", filter: "Filter", close: "Close", none: "None.", back: "Back to overview", addFilter: "+ Add filter", grouped: "Grouped list", tableView: "Table", boardView: "Board", days: "{n} days", connected: "Connected", notConfigured: "Not configured", download: "Download" },
    cases: { overview: "Case Overview", new: "New case", edit: "Edit case", search: "Search title, person, reference", allStatuses: "All statuses", noFound: "No cases found.", noInStatus: "No cases in this status.", title: "Title", caseId: "Case ID", type: "Type", progress: "Progress", reference: "Reference", name: "Name", status: "Status", noDescription: "No description.", assignee: "Assignee", deadline: "Deadline", open: "Open case", confirmDelete: "Delete this case?", dossier: "File", created: "Created", createdBy: "by {name}", updated: "Updated", links: "Links", companies: "Companies", persons: "Persons", attachments: "Attachments", upload: "Upload", noAttachments: "No attachments yet. Files are stored in the data volume.", createDoc: "Create document", createOff: "Create is not active. An administrator can enable it under Settings → Integrations.", noTemplatesLinked: "This case type has linked templates, but they have not been synced yet.", noTemplates: "No templates available. Sync recipes under Templates or link them to the case type.", pickTemplate: "Choose a template", openCreate: "Open in Create", createHint: "Case data is sent as prefill. Create opens in this tab to finish the document.", description: "Description", progressPct: "Progress (%)", priority: "Priority", generateDoc: "Generate document", generateInteractive: "Generate interactively", tabDetails: "Case details", tabDocuments: "Documents", leadTime: "Lead time", leadStart: "Lead time start date", plannedEnd: "Planned end date", stakeholders: "Stakeholders", more: "More", caseManager: "Case manager", noStakeholders: "No stakeholders linked.", confirmDeleteDoc: "Delete this document?", docUploaded: "Uploaded", docInCreate: "In Create", docCompleted: "Completed", docFailed: "Failed", docGenerating: "Generating", leadHint: "Together with the case type (lead time), this determines the planned end date.", stakeholderHint: "Add persons or companies as stakeholders.", searchStakeholder: "Search by name or email…", stakeholderPerson: "Person", stakeholderCompany: "Company", add: "Add", caseIdSoon: "Assigned when saved", createPayload: "Payload to Create" },
    persons: { overview: "Person Overview", new: "New person", edit: "Edit person", search: "Search name, email, ID", all: "All persons", noFound: "No persons found.", noInStatus: "No persons in this status.", name: "Name", personId: "Person ID", company: "Company", email: "Email", phone: "Phone", place: "City", cases: "Cases", noAddress: "No address", open: "Open person", firstName: "First name", lastName: "Last name", dob: "Date of birth", bsn: "BSN", address: "Address", postcode: "Postcode", keepBsn: "Leave empty to keep", storedEnc: "Stored encrypted", confirmAnon: "Anonymise personal data? Case history is kept.", anonymise: "Anonymise", confirmDelete: "Permanently delete this person?", show: "show", hide: "hide", linkedCases: "Linked cases", noCases: "No cases.", anonymised: "Anonymised", eyebrow: "Person", infix: "Infix", gender: "Gender", male: "Male", female: "Female", other: "Other", street: "Street", houseNo: "House number", country: "Country" },
    companies: { overview: "Company Overview", new: "New company", edit: "Edit company", search: "Search name, KvK, place", all: "All companies", noFound: "No companies found.", noInStatus: "No companies in this status.", name: "Name", companyId: "Company ID", place: "City", cases: "Cases", noAddress: "No address", open: "Open company", kvk: "KvK", phone: "Phone", email: "Email", address: "Address", postcode: "Postcode", notes: "Notes", confirmDelete: "Delete this company?", linkedCases: "Linked cases", noCases: "No cases.", eyebrow: "Company" },
    employees: { overview: "Employee Overview", new: "New employee", edit: "Edit employee", search: "Search name, number or email", allRoles: "All roles", noInRole: "No employees in this role.", name: "Name", email: "Email", role: "Role", department: "Department", open: "Open employee", firstName: "First name", lastName: "Last name", password: "Password", keepPassword: "Leave empty to keep", confirmDelete: "Delete this employee?", assignedCases: "Assigned cases", noCases: "No cases.", eyebrow: "Employees" },
    hr: { tabContact: "Contact details", contact: "Contact details", employment: "Employment", address: "Address", staffNo: "Personnel number", job: "Job title", location: "Location", startDate: "Date of employment", updated: "Updated", salutation: "Salutation", heer: "Mr.", mevrouw: "Ms.", dob: "Date of birth", scale: "Salary scale", salary: "Salary", companyCar: "Company car", yes: "Yes", no: "No", street: "Street", houseNo: "House number", postcode: "Postcode", city: "City", account: "Sign-in", passwordHint: "Leave empty if this person should not sign in." },
    audit: { overview: "Audit Overview", refresh: "Refresh", search: "Search actor, action, entity", all: "All entities", noEvents: "No events in this status.", time: "Time", user: "User", action: "Action", entity: "Entity", detail: "Detail" },
    entity: { zaak: "Cases", persoon: "Persons", bedrijf: "Companies", werknemer: "Employees", instellingen: "Settings", recipe: "Templates", document: "Documents", zaaktype: "Case types" },
    settings: { title: "Settings", general: "General", generalHint: "Organisation name, profile and numbering", caseTypes: "Case types", caseTypesHint: "Case types, lead time and templates", integrations: "Integrations", integrationsHint: "API, webhooks, unit and document output", templates: "Templates", templatesHint: "Create recipes used to generate documents", back: "‹ Back to settings", generalTitle: "General", generalLede: "Organisation name, application profile and how numbers are built.", orgName: "Organisation name", prefix: "Case number prefix", nextNumber: "Next number:", nextStaff: "Next personnel number:", save: "Save", demoTitle: "Sample data", demoLede: "Import sample persons and companies in {lang}. Existing records are kept; already imported entries are skipped.", demoImport: "Import sample data", demoConfirm: "Add sample persons and companies for the current language?" },
    caseTypes: { title: "Case types", lede: "Name, lead time and which Create templates belong to a type. On a case, only those templates are offered.", new: "+ New case type", empty: "No case types yet. Add one to categorise cases.", name: "Name", leadTime: "Lead time", templates: "Templates", cases: "Cases", edit: "Edit", newTitle: "New case type", editTitle: "Edit case type", formLede: "Lead time is used to suggest a deadline on a new case. Linked templates appear when generating a document.", leadDays: "Lead time (days)", noTemplates: "No templates yet. Sync them first under", templatesHint: "Only checked recipes are offered on cases of this type. Leave all unchecked to allow every template.", search: "Search templates", selectAll: "Select all", clear: "Clear", confirmDelete: "Delete this case type? Existing cases will be kept.", back: "‹ Back to case types", notFound: "This case type does not exist." },
    integrations: { title: "Integrations", lede: "Overview of connected integrations. Use Edit from the actions menu to configure Create. Turn off Active to pause temporarily, all settings are kept.", saveActive: "Save which integrations are active", integration: "Integration", summary: "Summary", active: "Active", actions: "Actions", edit: "Edit", test: "Test connection", sync: "Sync templates", back: "‹ Back to integrations" },
    create: { title: "Create", lede: "OAuth client credentials, unit and content source for OmniDocs Create.", baseUrl: "API base URL", clientId: "Client ID", clientSecret: "Client secret", keepSecret: "leave empty to keep", unitId: "Unit ID", contentSourceId: "Content source ID", publicUrl: "Public base URL (webhooks)", webhookHint: "Webhooks only work if Create can reach Zaakhub. Leave empty locally; the document then opens only in Create.", authDomain: "Auth domain", authDomainHint: "Appended as ?authDomain= when opening Create.", save: "Save connection", templates: "Templates ({n})", lastSync: "Last sync:", clientConfigured: "Client configured", clientMissing: "Client missing" },
    templates: { title: "Templates", lede: "Recipes from OmniDocs Create. Sync them and use them on a case to prepare a document.", sync: "Sync templates", notConfigured: "Create is not configured yet. Enter client, unit and content source under Settings → Integrations.", search: "Search templates", empty: "No templates yet. Save the connection and click Sync.", fields: "Fields", visibility: "Visibility", hidden: "Hidden", visible: "Visible", selected: "{n} selected", allAllowed: "All allowed" },
    error: { title: "Error", notFound: "Not found", notFoundPage: "This page does not exist.", notFoundCase: "This case does not exist.", notFoundCompany: "This company does not exist.", notFoundPerson: "This person does not exist.", notFoundEmployee: "This employee does not exist.", forbidden: "No access", forbiddenMsg: "Your role cannot open this page.", server: "Something went wrong. Try again or check the container logs." },
    toast: { caseCreated: "Case created", caseSaved: "Case saved", caseDeleted: "Case deleted", noFile: "No file selected", attachmentAdded: "Attachment added", attachmentDeleted: "Document deleted", pickTemplate: "Choose a template", createOff: "Create is not active or not configured", noFinalize: "Document prepared, but Create did not return a finalize URL", documentGenerated: "Document generated", noFileUri: "Document generated, but Create did not return a file URI", companySaved: "Company saved", companyDeleted: "Company deleted", personSaved: "Person saved", personAnon: "Data anonymised", personDeleted: "Person deleted", employeeSaved: "Employee saved", employeeDeleted: "Employee deleted", cannotDeleteSelf: "You cannot delete yourself", settingsSaved: "Settings saved", typeSaved: "Case type saved", typeDeleted: "Case type deleted", integrationsSaved: "Active integrations saved", createSaved: "Create connection saved", azureSaved: "Microsoft Entra ID connection saved", fillCreate: "Enter client, unit and content source", testOk: "Connection OK · {n} templates found", testFail: "Connection failed: {msg}", configureFirst: "Configure Create first", synced: "{n} templates synced", syncFail: "Sync failed: {msg}", demoImported: "Added {companies} companies and {persons} persons.", demoAlready: "Sample data for this language is already in the registry." },
    validation: { nameRequired: "Name is required.", passwordRequired: "A password is required for a new employee.", passwordMismatch: "Passwords do not match.", passwordShort: "Use at least 8 characters." },
  },
  da: {
    nav: { home: "Hjem", dashboard: "Dashboard", cases: "Sager", naw: "Register", persons: "Personer", companies: "Virksomheder", admin: "Administrator", employees: "Medarbejdere", audit: "Revisionslog", settings: "Indstillinger", newCase: "+ Ny sag", newEmployee: "+ Ny medarbejder", signOut: "Log ud", search: "Søg personer, virksomheder" },
    search: { placeholder: "Søg personer, virksomheder, sager…", nothing: "Ingen resultater" },
    login: { title: "Log ind", email: "E-mail", password: "Adgangskode", continue: "Fortsæt", demo: "Demo", error: "Forkert e-mail eller adgangskode.", microsoft: "Log ind med Microsoft", orEmail: "eller log ind med e-mail" },
    onboard: { title: "Velkommen", lede: "Et par trin, så arbejdsområdet er klar.", stepOf: "Trin {n} af {total}", org: "Organisation", orgLede: "Applikationsnavn og hvordan sagsnumre bygges.", profile: "Profil", profileLede: "Vælg om arbejdsområdet er et sagsystem, et HR-system eller begge dele.", profileCases: "Sagsbehandling", profileCasesHint: "Sager, personer og virksomheder. Medarbejdere forbliver systembrugere.", profileHr: "HR", profileHrHint: "Hold styr på medarbejderdata, kontrakter og HR-dokumenter.", profileBoth: "Sager og HR", profileBothHint: "Sagsbehandling plus et medarbejderregister.", personeelPrefix: "Præfiks for personalenummer", admin: "Administrator", adminLede: "Denne konto kan styre indstillinger, brugere og integrationer.", create: "Create", createLede: "Tilslut OmniDocs Create for at oprette dokumenter. Du kan springe over og gøre det senere under Indstillinger.", azure: "Microsoft Entra ID", azureLede: "Valgfri login med arbejdskonti. Du kan springe over og gøre det senere under Indstillinger.", next: "Fortsæt", skip: "Spring over", finish: "Afslut opsætning", back: "Tilbage", passwordConfirm: "Bekræft adgangskode" },
    azure: { title: "Microsoft Entra ID", lede: "Lad medarbejdere logge ind med deres Microsoft-arbejdskonto.", tenantId: "Tenant-ID", clientId: "Program (klient) ID", clientSecret: "Klienthemmelighed", keepSecret: "lad stå tom for at beholde", redirectUri: "Redirect URI", redirectHint: "Registrer denne URI som Web redirect i Entra-appregistreringen.", save: "Gem forbindelse", clientConfigured: "App registreret", clientMissing: "App mangler" },
    dash: { title: "Dashboard", lede: "Overblik over sager, dokumenter og dit register.", hrLede: "Overblik over medarbejdere og dokumenter.", total: "Sager i alt", open: "Åbne", progress: "I gang", closed: "Afsluttede", split: "Fordelt på status", waiting: "Afventer", overdue: "Frist overskredet", noOverdue: "Ingen forsinkede sager.", overdueBadge: "Overskredet", viewAll: "Se alle sager", recentCases: "Seneste sager", noCases: "Ingen sager endnu.", recentDocs: "Seneste dokumenter", noDocs: "Ingen dokumenter uploadet endnu.", board: "Tavle", recentEmployees: "Seneste medarbejdere", noEmployees: "Ingen medarbejdere endnu.", viewEmployees: "Se alle medarbejdere" },
    status: { nieuw: "Ny", in_behandeling: "I gang", wacht_op_info: "Afventer", afgerond: "Afsluttet", geannuleerd: "Annulleret" },
    priority: { laag: "Lav", normaal: "Normal", hoog: "Høj", urgent: "Haster" },
    role: { admin: "Administrator", zaakmanager: "Sagsbehandler", medewerker: "Medarbejder" },
    group: { open: "Åbne", progress: "I gang", closed: "Afsluttede" },
    personGroup: { active: "Aktive", anon: "Anonymiseret" },
    companyGroup: { linked: "Med sager", idle: "Uden sager" },
    common: { save: "Gem", cancel: "Annuller", edit: "Rediger", delete: "Slet", apply: "Anvend", filter: "Filtrer", close: "Luk", none: "Ingen.", back: "Tilbage til oversigten", addFilter: "+ Tilføj filter", grouped: "Grupperet liste", tableView: "Tabel", boardView: "Tavle", days: "{n} dage", connected: "Forbundet", notConfigured: "Ikke konfigureret", download: "Download" },
    cases: { overview: "Sagsoversigt", new: "Ny sag", edit: "Rediger sag", search: "Søg titel, person, reference", allStatuses: "Alle statusser", noFound: "Ingen sager fundet.", noInStatus: "Ingen sager i denne status.", title: "Titel", caseId: "Sagsnr.", type: "Type", progress: "Fremdrift", reference: "Reference", name: "Navn", status: "Status", noDescription: "Ingen beskrivelse.", assignee: "Ansvarlig", deadline: "Frist", open: "Åbn sag", confirmDelete: "Slet denne sag?", dossier: "Dossier", created: "Oprettet", createdBy: "af {name}", updated: "Opdateret", links: "Koblinger", companies: "Virksomheder", persons: "Personer", attachments: "Vedhæftninger", upload: "Upload", noAttachments: "Ingen vedhæftninger endnu. Filer gemmes i data-volume.", createDoc: "Opret dokument", createOff: "Create er ikke aktiv. En administrator kan slå det til under Indstillinger → Integrationer.", noTemplatesLinked: "Sagstypen har tilknyttede skabeloner, som endnu ikke er synkroniseret.", noTemplates: "Ingen skabeloner. Synkroniser under Skabeloner eller knyt dem til sagstypen.", pickTemplate: "Vælg en skabelon", openCreate: "Åbn i Create", createHint: "Sagsdata sendes som forudfyldning. Create åbner i denne fane.", description: "Beskrivelse", progressPct: "Fremdrift (%)", priority: "Prioritet", generateDoc: "Generer dokument", generateInteractive: "Generer interaktivt", tabDetails: "Sagsdetaljer", tabDocuments: "Dokumenter", leadTime: "Frist", leadStart: "Startdato for frist", plannedEnd: "Planlagt slutdato", stakeholders: "Interessenter", more: "Mere", caseManager: "Sagsbehandler", noStakeholders: "Ingen interessenter tilknyttet.", confirmDeleteDoc: "Slet dette dokument?", docUploaded: "Uploadet", docInCreate: "I Create", docCompleted: "Afsluttet", docFailed: "Mislykkedes", docGenerating: "Genererer", leadHint: "Sammen med sagstypen (frist) fastlægger dette den planlagte slutdato.", stakeholderHint: "Tilføj personer eller virksomheder som interessenter.", searchStakeholder: "Søg på navn eller e-mail…", stakeholderPerson: "Person", stakeholderCompany: "Virksomhed", add: "Tilføj", caseIdSoon: "Tildeles ved gem", createPayload: "Payload til Create" },
    persons: { overview: "Personeoversigt", new: "Ny person", edit: "Rediger person", search: "Søg navn, e-mail, ID", all: "Alle personer", noFound: "Ingen personer fundet.", noInStatus: "Ingen personer i denne status.", name: "Navn", personId: "Person-ID", company: "Virksomhed", email: "E-mail", phone: "Telefon", place: "By", cases: "Sager", noAddress: "Ingen adresse", open: "Åbn person", firstName: "Fornavn", lastName: "Efternavn", dob: "Fødselsdato", bsn: "CPR/BSN", address: "Adresse", postcode: "Postnr.", keepBsn: "Lad stå tom for at beholde", storedEnc: "Gemmes krypteret", confirmAnon: "Anonymiser persondata? Sagshistorik beholdes.", anonymise: "Anonymiser", confirmDelete: "Slet personen permanent?", show: "vis", hide: "skjul", linkedCases: "Tilknyttede sager", noCases: "Ingen sager.", anonymised: "Anonymiseret", eyebrow: "Person", infix: "Mellemnavn", gender: "Køn", male: "Mand", female: "Kvinde", other: "Andet", street: "Gade", houseNo: "Husnr.", country: "Land" },
    companies: { overview: "Virksomhedsoversigt", new: "Ny virksomhed", edit: "Rediger virksomhed", search: "Søg navn, CVR, by", all: "Alle virksomheder", noFound: "Ingen virksomheder fundet.", noInStatus: "Ingen virksomheder i denne status.", name: "Navn", companyId: "Virksomheds-ID", place: "By", cases: "Sager", noAddress: "Ingen adresse", open: "Åbn virksomhed", kvk: "CVR/KvK", phone: "Telefon", email: "E-mail", address: "Adresse", postcode: "Postnr.", notes: "Noter", confirmDelete: "Slet denne virksomhed?", linkedCases: "Tilknyttede sager", noCases: "Ingen sager.", eyebrow: "Virksomhed" },
    employees: { overview: "Medarbejderoversigt", new: "Ny medarbejder", edit: "Rediger medarbejder", search: "Søg navn, nummer eller e-mail", allRoles: "Alle roller", noInRole: "Ingen medarbejdere i denne rolle.", name: "Navn", email: "E-mail", role: "Rolle", department: "Afdeling", open: "Åbn medarbejder", firstName: "Fornavn", lastName: "Efternavn", password: "Adgangskode", keepPassword: "Lad stå tom for at beholde", confirmDelete: "Slet denne medarbejder?", assignedCases: "Tildelte sager", noCases: "Ingen sager.", eyebrow: "Medarbejdere" },
    hr: { tabContact: "Kontaktoplysninger", contact: "Kontaktoplysninger", employment: "Ansættelse", address: "Adresse", staffNo: "Personalenummer", job: "Stilling", location: "Lokation", startDate: "Ansættelsesdato", updated: "Opdateret", salutation: "Tiltale", heer: "Hr.", mevrouw: "Fru", dob: "Fødselsdato", scale: "Løntrin", salary: "Løn", companyCar: "Firmabil", yes: "Ja", no: "Nej", street: "Gade", houseNo: "Husnr.", postcode: "Postnr.", city: "By", account: "Login", passwordHint: "Lad stå tom, hvis personen ikke skal logge ind." },
    audit: { overview: "Revisionslog", refresh: "Opdater", search: "Søg bruger, handling, enhed", all: "Alle enheder", noEvents: "Ingen hændelser i denne status.", time: "Tid", user: "Bruger", action: "Handling", entity: "Enhed", detail: "Detalje" },
    entity: { zaak: "Sager", persoon: "Personer", bedrijf: "Virksomheder", werknemer: "Medarbejdere", instellingen: "Indstillinger", recipe: "Skabeloner", document: "Dokumenter", zaaktype: "Sagstyper" },
    settings: { title: "Indstillinger", general: "Generelt", generalHint: "Organisationsnavn, profil og numre", caseTypes: "Sagstyper", caseTypesHint: "Sagstyper, frist og skabeloner", integrations: "Integrationer", integrationsHint: "API, webhooks, unit og dokumentoutput", templates: "Skabeloner", templatesHint: "Create-skabeloner til dokumenter", back: "‹ Tilbage til indstillinger", generalTitle: "Generelt", generalLede: "Organisationsnavn, applikationsprofil og hvordan numre bygges.", orgName: "Organisationsnavn", prefix: "Præfiks for sagsnummer", nextNumber: "Næste nummer:", nextStaff: "Næste personalenummer:", save: "Gem", demoTitle: "Eksempeldata", demoLede: "Importer eksempelpersoner og -virksomheder på {lang}. Eksisterende poster beholdes; allerede importerede poster springes over.", demoImport: "Importer eksempeldata", demoConfirm: "Tilføj eksempelpersoner og -virksomheder for det aktuelle sprog?" },
    caseTypes: { title: "Sagstyper", lede: "Navn, frist og hvilke Create-skabeloner der hører til en type.", new: "+ Ny sagstype", empty: "Ingen sagstyper endnu. Opret en for at kategorisere sager.", name: "Navn", leadTime: "Frist", templates: "Skabeloner", cases: "Sager", edit: "Rediger", newTitle: "Ny sagstype", editTitle: "Rediger sagstype", formLede: "Fristen foreslår en deadline på en ny sag. Tilknyttede skabeloner vises ved dokumentoprettelse.", leadDays: "Frist (dage)", noTemplates: "Ingen skabeloner endnu. Synkroniser først under", templatesHint: "Kun markerede skabeloner tilbydes på sager af denne type. Ingen markering = alle skabeloner.", search: "Søg skabeloner", selectAll: "Vælg alle", clear: "Ryd", confirmDelete: "Slet denne sagstype? Eksisterende sager beholdes.", back: "‹ Tilbage til sagstyper", notFound: "Denne sagstype findes ikke." },
    integrations: { title: "Integrationer", lede: "Oversigt over tilknyttede integrationer. Brug Rediger i handlingsmenuen til at konfigurere Create. Slå Aktiv fra for at pause midlertidigt.", saveActive: "Gem hvilke integrationer der er aktive", integration: "Integration", summary: "Resume", active: "Aktiv", actions: "Handlinger", edit: "Rediger", test: "Test forbindelse", sync: "Synkroniser skabeloner", back: "‹ Tilbage til integrationer" },
    create: { title: "Create", lede: "OAuth-klientoplysninger, unit og content source til OmniDocs Create.", baseUrl: "API-basis-URL", clientId: "Client ID", clientSecret: "Client secret", keepSecret: "lad stå tom for at beholde", unitId: "Unit ID", contentSourceId: "Content source ID", publicUrl: "Offentlig basis-URL (webhooks)", webhookHint: "Webhooks virker kun, hvis Create kan nå Zaakhub. Lad stå tom lokalt.", authDomain: "Auth-domæne", authDomainHint: "Tilføjes som ?authDomain= når Create åbnes.", save: "Gem forbindelse", templates: "Skabeloner ({n})", lastSync: "Seneste sync:", clientConfigured: "Klient konfigureret", clientMissing: "Klient mangler" },
    templates: { title: "Skabeloner", lede: "Recipes fra OmniDocs Create. Synkroniser dem og brug dem på en sag.", sync: "Synkroniser skabeloner", notConfigured: "Create er ikke konfigureret. Udfyld client, unit og content source under Indstillinger → Integrationer.", search: "Søg skabeloner", empty: "Ingen skabeloner endnu. Gem forbindelsen og klik Synkroniser.", fields: "Felter", visibility: "Synlighed", hidden: "Skjult", visible: "Synlig", selected: "{n} valgt", allAllowed: "Alle tilladt" },
    error: { title: "Fejl", notFound: "Ikke fundet", notFoundPage: "Denne side findes ikke.", notFoundCase: "Denne sag findes ikke.", notFoundCompany: "Denne virksomhed findes ikke.", notFoundPerson: "Denne person findes ikke.", notFoundEmployee: "Denne medarbejder findes ikke.", forbidden: "Ingen adgang", forbiddenMsg: "Din rolle har ikke rettigheder til denne side.", server: "Noget gik galt. Prøv igen eller tjek containerloggene." },
    toast: { caseCreated: "Sag oprettet", caseSaved: "Sag gemt", caseDeleted: "Sag slettet", noFile: "Ingen fil valgt", attachmentAdded: "Vedhæftning tilføjet", attachmentDeleted: "Dokument slettet", pickTemplate: "Vælg en skabelon", createOff: "Create er ikke aktiv eller ikke konfigureret", noFinalize: "Dokument forberedt, men Create returnerede ingen finalize-URL", documentGenerated: "Dokument genereret", noFileUri: "Dokument genereret, men Create returnerede ingen file URI", companySaved: "Virksomhed gemt", companyDeleted: "Virksomhed slettet", personSaved: "Person gemt", personAnon: "Data anonymiseret", personDeleted: "Person slettet", employeeSaved: "Medarbejder gemt", employeeDeleted: "Medarbejder slettet", cannotDeleteSelf: "Du kan ikke slette dig selv", settingsSaved: "Indstillinger gemt", typeSaved: "Sagstype gemt", typeDeleted: "Sagstype slettet", integrationsSaved: "Aktive integrationer gemt", createSaved: "Create-forbindelse gemt", azureSaved: "Microsoft Entra ID-forbindelse gemt", fillCreate: "Udfyld client, unit og content source", testOk: "Forbindelse OK · {n} skabeloner fundet", testFail: "Forbindelse mislykkedes: {msg}", configureFirst: "Konfigurer Create først", synced: "{n} skabeloner synkroniseret", syncFail: "Synkronisering mislykkedes: {msg}", demoImported: "Tilføjede {companies} virksomheder og {persons} personer.", demoAlready: "Eksempeldata for dette sprog findes allerede i registret." },
    validation: { nameRequired: "Navn er påkrævet.", passwordRequired: "Adgangskode er påkrævet for en ny medarbejder.", passwordMismatch: "Adgangskoderne er ikke ens.", passwordShort: "Brug mindst 8 tegn." },
  },
  de: {
    nav: { home: "Start", dashboard: "Dashboard", cases: "Fälle", naw: "Register", persons: "Personen", companies: "Unternehmen", admin: "Administration", employees: "Mitarbeiter", audit: "Prüfprotokoll", settings: "Einstellungen", newCase: "+ Neuer Fall", newEmployee: "+ Neuer Mitarbeiter", signOut: "Abmelden", search: "Personen, Unternehmen suchen" },
    search: { placeholder: "Personen, Unternehmen, Fälle suchen…", nothing: "Nichts gefunden" },
    login: { title: "Anmelden", email: "E-Mail", password: "Passwort", continue: "Weiter", demo: "Demo", error: "Falsche E-Mail oder Passwort.", microsoft: "Mit Microsoft anmelden", orEmail: "oder mit E-Mail anmelden" },
    onboard: { title: "Willkommen", lede: "Ein paar Schritte, dann ist der Arbeitsbereich bereit.", stepOf: "Schritt {n} von {total}", org: "Organisation", orgLede: "Anwendungsname und Aufbau der Fallnummern.", profile: "Profil", profileLede: "Wählen Sie, ob dieser Arbeitsbereich ein Fallsystem, ein HR-System oder beides ist.", profileCases: "Fallbearbeitung", profileCasesHint: "Fälle, Personen und Unternehmen. Mitarbeiter bleiben Systembenutzer.", profileHr: "HR", profileHrHint: "Mitarbeiterdaten, Verträge und HR-Dokumente führen.", profileBoth: "Fälle und HR", profileBothHint: "Fallbearbeitung plus Mitarbeiterregister.", personeelPrefix: "Präfix der Personalnummer", admin: "Administrator", adminLede: "Dieses Konto kann Einstellungen, Benutzer und Integrationen verwalten.", create: "Create", createLede: "Verbinden Sie OmniDocs Create, um Dokumente zu erzeugen. Sie können das überspringen und später unter Einstellungen nachholen.", azure: "Microsoft Entra ID", azureLede: "Optionale Anmeldung mit Arbeitskonten. Sie können das überspringen und später unter Einstellungen nachholen.", next: "Weiter", skip: "Vorerst überspringen", finish: "Einrichtung abschließen", back: "Zurück", passwordConfirm: "Passwort bestätigen" },
    azure: { title: "Microsoft Entra ID", lede: "Mitarbeitende mit ihrem Microsoft-Arbeitskonto anmelden.", tenantId: "Mandanten-ID", clientId: "Anwendungs-ID (Client)", clientSecret: "Geheimer Clientschlüssel", keepSecret: "leer lassen zum Behalten", redirectUri: "Umleitungs-URI", redirectHint: "Tragen Sie diese URI als Web-Umleitung in der Entra-App-Registrierung ein.", save: "Verbindung speichern", clientConfigured: "App registriert", clientMissing: "App fehlt" },
    dash: { title: "Dashboard", lede: "Überblick über Fälle, Dokumente und Ihr Register.", hrLede: "Überblick über Mitarbeitende und Dokumente.", total: "Fälle gesamt", open: "Offen", progress: "In Bearbeitung", closed: "Abgeschlossen", split: "Nach Status", waiting: "Wartend", overdue: "Frist überschritten", noOverdue: "Keine überfälligen Fälle.", overdueBadge: "Überfällig", viewAll: "Alle Fälle", recentCases: "Aktuelle Fälle", noCases: "Noch keine Fälle.", recentDocs: "Aktuelle Dokumente", noDocs: "Noch keine Dokumente hochgeladen.", board: "Board", recentEmployees: "Aktuelle Mitarbeitende", noEmployees: "Noch keine Mitarbeitenden.", viewEmployees: "Alle Mitarbeitenden" },
    status: { nieuw: "Neu", in_behandeling: "In Bearbeitung", wacht_op_info: "Wartend", afgerond: "Abgeschlossen", geannuleerd: "Storniert" },
    priority: { laag: "Niedrig", normaal: "Normal", hoog: "Hoch", urgent: "Dringend" },
    role: { admin: "Administrator", zaakmanager: "Fallmanager", medewerker: "Mitarbeiter" },
    group: { open: "Offen", progress: "In Bearbeitung", closed: "Abgeschlossen" },
    personGroup: { active: "Aktiv", anon: "Anonymisiert" },
    companyGroup: { linked: "Mit Fällen", idle: "Ohne Fälle" },
    common: { save: "Speichern", cancel: "Abbrechen", edit: "Bearbeiten", delete: "Löschen", apply: "Anwenden", filter: "Filtern", close: "Schließen", none: "Keine.", back: "Zurück zur Übersicht", addFilter: "+ Filter hinzufügen", grouped: "Gruppierte Liste", tableView: "Tabelle", boardView: "Board", days: "{n} Tage", connected: "Verbunden", notConfigured: "Nicht konfiguriert", download: "Download" },
    cases: { overview: "Fallübersicht", new: "Neuer Fall", edit: "Fall bearbeiten", search: "Titel, Person, Referenz suchen", allStatuses: "Alle Status", noFound: "Keine Fälle gefunden.", noInStatus: "Keine Fälle in diesem Status.", title: "Titel", caseId: "Fall-ID", type: "Typ", progress: "Fortschritt", reference: "Referenz", name: "Name", status: "Status", noDescription: "Keine Beschreibung.", assignee: "Bearbeiter", deadline: "Frist", open: "Fall öffnen", confirmDelete: "Diesen Fall löschen?", dossier: "Akte", created: "Erstellt", createdBy: "von {name}", updated: "Geändert", links: "Verknüpfungen", companies: "Unternehmen", persons: "Personen", attachments: "Anhänge", upload: "Hochladen", noAttachments: "Noch keine Anhänge. Dateien liegen im Daten-Volume.", createDoc: "Dokument erstellen", createOff: "Create ist nicht aktiv. Ein Administrator kann es unter Einstellungen → Integrationen einschalten.", noTemplatesLinked: "Dieser Falltyp hat Vorlagen, die noch nicht synchronisiert sind.", noTemplates: "Keine Vorlagen. Unter Vorlagen synchronisieren oder dem Falltyp zuordnen.", pickTemplate: "Vorlage wählen", openCreate: "In Create öffnen", createHint: "Falldaten werden als Prefill gesendet. Create öffnet sich in diesem Tab.", description: "Beschreibung", progressPct: "Fortschritt (%)", priority: "Priorität", generateDoc: "Dokument erzeugen", generateInteractive: "Interaktiv erzeugen", tabDetails: "Falldetails", tabDocuments: "Dokumente", leadTime: "Durchlaufzeit", leadStart: "Startdatum Durchlaufzeit", plannedEnd: "Geplantes Enddatum", stakeholders: "Beteiligte", more: "Mehr", caseManager: "Fallmanager", noStakeholders: "Keine Beteiligten verknüpft.", confirmDeleteDoc: "Dieses Dokument löschen?", docUploaded: "Hochgeladen", docInCreate: "In Create", docCompleted: "Abgeschlossen", docFailed: "Fehlgeschlagen", docGenerating: "Wird erstellt", leadHint: "Zusammen mit dem Falltyp (Frist) ergibt sich das geplante Enddatum.", stakeholderHint: "Personen oder Unternehmen als Beteiligte hinzufügen.", searchStakeholder: "Nach Name oder E-Mail suchen…", stakeholderPerson: "Person", stakeholderCompany: "Unternehmen", add: "Hinzufügen", caseIdSoon: "Wird beim Speichern vergeben", createPayload: "Payload an Create" },
    persons: { overview: "Personenübersicht", new: "Neue Person", edit: "Person bearbeiten", search: "Name, E-Mail, ID suchen", all: "Alle Personen", noFound: "Keine Personen gefunden.", noInStatus: "Keine Personen in diesem Status.", name: "Name", personId: "Personen-ID", company: "Unternehmen", email: "E-Mail", phone: "Telefon", place: "Ort", cases: "Fälle", noAddress: "Keine Adresse", open: "Person öffnen", firstName: "Vorname", lastName: "Nachname", dob: "Geburtsdatum", bsn: "BSN", address: "Adresse", postcode: "PLZ", keepBsn: "Leer lassen zum Behalten", storedEnc: "Verschlüsselt gespeichert", confirmAnon: "Personendaten anonymisieren? Fallhistorie bleibt erhalten.", anonymise: "Anonymisieren", confirmDelete: "Person endgültig löschen?", show: "anzeigen", hide: "verbergen", linkedCases: "Verknüpfte Fälle", noCases: "Keine Fälle.", anonymised: "Anonymisiert", eyebrow: "Person", infix: "Namenszusatz", gender: "Geschlecht", male: "Männlich", female: "Weiblich", other: "Divers", street: "Straße", houseNo: "Hausnummer", country: "Land" },
    companies: { overview: "Unternehmensübersicht", new: "Neues Unternehmen", edit: "Unternehmen bearbeiten", search: "Name, KvK, Ort suchen", all: "Alle Unternehmen", noFound: "Keine Unternehmen gefunden.", noInStatus: "Keine Unternehmen in diesem Status.", name: "Name", companyId: "Unternehmens-ID", place: "Ort", cases: "Fälle", noAddress: "Keine Adresse", open: "Unternehmen öffnen", kvk: "KvK", phone: "Telefon", email: "E-Mail", address: "Adresse", postcode: "PLZ", notes: "Notizen", confirmDelete: "Dieses Unternehmen löschen?", linkedCases: "Verknüpfte Fälle", noCases: "Keine Fälle.", eyebrow: "Unternehmen" },
    employees: { overview: "Mitarbeiterübersicht", new: "Neuer Mitarbeiter", edit: "Mitarbeiter bearbeiten", search: "Name, Nummer oder E-Mail suchen", allRoles: "Alle Rollen", noInRole: "Keine Mitarbeiter in dieser Rolle.", name: "Name", email: "E-Mail", role: "Rolle", department: "Abteilung", open: "Mitarbeiter öffnen", firstName: "Vorname", lastName: "Nachname", password: "Passwort", keepPassword: "Leer lassen zum Behalten", confirmDelete: "Diesen Mitarbeiter löschen?", assignedCases: "Zugewiesene Fälle", noCases: "Keine Fälle.", eyebrow: "Mitarbeiter" },
    hr: { tabContact: "Kontaktdaten", contact: "Kontaktdaten", employment: "Beschäftigung", address: "Adresse", staffNo: "Personalnummer", job: "Stellenbezeichnung", location: "Standort", startDate: "Eintrittsdatum", updated: "Aktualisiert", salutation: "Anrede", heer: "Herr", mevrouw: "Frau", dob: "Geburtsdatum", scale: "Eingruppierung", salary: "Gehalt", companyCar: "Dienstwagen", yes: "Ja", no: "Nein", street: "Straße", houseNo: "Hausnummer", postcode: "PLZ", city: "Ort", account: "Anmeldung", passwordHint: "Leer lassen, wenn diese Person sich nicht anmelden soll." },
    audit: { overview: "Prüfprotokoll", refresh: "Aktualisieren", search: "Akteur, Aktion, Objekt suchen", all: "Alle Objekte", noEvents: "Keine Ereignisse in diesem Status.", time: "Zeit", user: "Benutzer", action: "Aktion", entity: "Objekt", detail: "Detail" },
    entity: { zaak: "Fälle", persoon: "Personen", bedrijf: "Unternehmen", werknemer: "Mitarbeiter", instellingen: "Einstellungen", recipe: "Vorlagen", document: "Dokumente", zaaktype: "Falltypen" },
    settings: { title: "Einstellungen", general: "Allgemein", generalHint: "Organisationsname, Profil und Nummern", caseTypes: "Falltypen", caseTypesHint: "Falltypen, Frist und Vorlagen", integrations: "Integrationen", integrationsHint: "API, Webhooks, Unit und Dokumentausgabe", templates: "Vorlagen", templatesHint: "Create-Vorlagen für Dokumente", back: "‹ Zurück zu Einstellungen", generalTitle: "Allgemein", generalLede: "Organisationsname, Anwendungsprofil und Aufbau der Nummern.", orgName: "Organisationsname", prefix: "Präfix der Fallnummer", nextNumber: "Nächste Nummer:", nextStaff: "Nächste Personalnummer:", save: "Speichern", demoTitle: "Beispieldaten", demoLede: "Beispielpersonen und -unternehmen auf {lang} importieren. Vorhandene Datensätze bleiben erhalten; bereits importierte Einträge werden übersprungen.", demoImport: "Beispieldaten importieren", demoConfirm: "Beispielpersonen und -unternehmen für die aktuelle Sprache hinzufügen?" },
    caseTypes: { title: "Falltypen", lede: "Name, Frist und welche Create-Vorlagen zu einem Typ gehören.", new: "+ Neuer Falltyp", empty: "Noch keine Falltypen. Legen Sie einen an, um Fälle zu kategorisieren.", name: "Name", leadTime: "Frist", templates: "Vorlagen", cases: "Fälle", edit: "Bearbeiten", newTitle: "Neuer Falltyp", editTitle: "Falltyp bearbeiten", formLede: "Die Frist schlägt eine Deadline bei einem neuen Fall vor. Verknüpfte Vorlagen erscheinen bei der Dokumenterstellung.", leadDays: "Frist (Tage)", noTemplates: "Noch keine Vorlagen. Zuerst synchronisieren unter", templatesHint: "Nur markierte Vorlagen werden bei Fällen dieses Typs angeboten. Nichts markiert = alle Vorlagen.", search: "Vorlagen suchen", selectAll: "Alle auswählen", clear: "Leeren", confirmDelete: "Diesen Falltyp löschen? Bestehende Fälle bleiben erhalten.", back: "‹ Zurück zu Falltypen", notFound: "Dieser Falltyp existiert nicht." },
    integrations: { title: "Integrationen", lede: "Übersicht verbundener Integrationen. Über Bearbeiten im Aktionsmenü Create konfigurieren. Aktiv aus, um vorübergehend zu pausieren.", saveActive: "Speichern, welche Integrationen aktiv sind", integration: "Integration", summary: "Zusammenfassung", active: "Aktiv", actions: "Aktionen", edit: "Bearbeiten", test: "Verbindung testen", sync: "Vorlagen synchronisieren", back: "‹ Zurück zu Integrationen" },
    create: { title: "Create", lede: "OAuth-Clientdaten, Unit und Content Source für OmniDocs Create.", baseUrl: "API-Basis-URL", clientId: "Client-ID", clientSecret: "Client-Secret", keepSecret: "leer lassen zum Behalten", unitId: "Unit-ID", contentSourceId: "Content-Source-ID", publicUrl: "Öffentliche Basis-URL (Webhooks)", webhookHint: "Webhooks funktionieren nur, wenn Create Zaakhub erreichen kann. Lokal leer lassen.", authDomain: "Auth-Domain", authDomainHint: "Wird als ?authDomain= angehängt, wenn Create geöffnet wird.", save: "Verbindung speichern", templates: "Vorlagen ({n})", lastSync: "Letzte Sync:", clientConfigured: "Client konfiguriert", clientMissing: "Client fehlt" },
    templates: { title: "Vorlagen", lede: "Rezepte aus OmniDocs Create. Synchronisieren und auf einem Fall verwenden.", sync: "Vorlagen synchronisieren", notConfigured: "Create ist noch nicht konfiguriert. Client, Unit und Content Source unter Einstellungen → Integrationen eintragen.", search: "Vorlagen suchen", empty: "Noch keine Vorlagen. Verbindung speichern und Synchronisieren klicken.", fields: "Felder", visibility: "Sichtbarkeit", hidden: "Verborgen", visible: "Sichtbar", selected: "{n} ausgewählt", allAllowed: "Alle erlaubt" },
    error: { title: "Fehler", notFound: "Nicht gefunden", notFoundPage: "Diese Seite existiert nicht.", notFoundCase: "Dieser Fall existiert nicht.", notFoundCompany: "Dieses Unternehmen existiert nicht.", notFoundPerson: "Diese Person existiert nicht.", notFoundEmployee: "Dieser Mitarbeiter existiert nicht.", forbidden: "Kein Zugriff", forbiddenMsg: "Ihre Rolle hat keine Rechte für diese Seite.", server: "Etwas ist schiefgelaufen. Erneut versuchen oder die Container-Logs prüfen." },
    toast: { caseCreated: "Fall erstellt", caseSaved: "Fall gespeichert", caseDeleted: "Fall gelöscht", noFile: "Keine Datei gewählt", attachmentAdded: "Anhang hinzugefügt", attachmentDeleted: "Dokument gelöscht", pickTemplate: "Vorlage wählen", createOff: "Create ist nicht aktiv oder nicht konfiguriert", noFinalize: "Dokument vorbereitet, aber Create lieferte keine Finalize-URL", documentGenerated: "Dokument erzeugt", noFileUri: "Dokument erzeugt, aber Create lieferte keine fileUri", companySaved: "Unternehmen gespeichert", companyDeleted: "Unternehmen gelöscht", personSaved: "Person gespeichert", personAnon: "Daten anonymisiert", personDeleted: "Person gelöscht", employeeSaved: "Mitarbeiter gespeichert", employeeDeleted: "Mitarbeiter gelöscht", cannotDeleteSelf: "Sie können sich nicht selbst löschen", settingsSaved: "Einstellungen gespeichert", typeSaved: "Falltyp gespeichert", typeDeleted: "Falltyp gelöscht", integrationsSaved: "Aktive Integrationen gespeichert", createSaved: "Create-Verbindung gespeichert", azureSaved: "Microsoft Entra ID-Verbindung gespeichert", fillCreate: "Client, Unit und Content Source eintragen", testOk: "Verbindung OK · {n} Vorlagen gefunden", testFail: "Verbindung fehlgeschlagen: {msg}", configureFirst: "Zuerst Create konfigurieren", synced: "{n} Vorlagen synchronisiert", syncFail: "Synchronisierung fehlgeschlagen: {msg}", demoImported: "{companies} Unternehmen und {persons} Personen hinzugefügt.", demoAlready: "Beispieldaten für diese Sprache sind bereits im Register." },
    validation: { nameRequired: "Name ist erforderlich.", passwordRequired: "Ein Passwort ist für einen neuen Mitarbeiter erforderlich.", passwordMismatch: "Passwörter stimmen nicht überein.", passwordShort: "Mindestens 8 Zeichen verwenden." },
  },
  nl: {
    nav: { home: "Home", dashboard: "Dashboard", cases: "Zaken", naw: "NAW", persons: "Personen", companies: "Bedrijven", admin: "Beheer", employees: "Werknemers", audit: "Auditlog", settings: "Instellingen", newCase: "+ Nieuwe zaak", newEmployee: "+ Nieuwe werknemer", signOut: "Uitloggen", search: "Personen, bedrijven zoeken" },
    search: { placeholder: "Personen, bedrijven, zaken zoeken…", nothing: "Niets gevonden" },
    login: { title: "Aanmelden", email: "E-mail", password: "Wachtwoord", continue: "Doorgaan", demo: "Demo", error: "Onjuiste e-mail of wachtwoord.", microsoft: "Aanmelden met Microsoft", orEmail: "of aanmelden met e-mail" },
    onboard: { title: "Welkom", lede: "Een paar stappen om deze werkruimte klaar te zetten.", stepOf: "Stap {n} van {total}", org: "Organisatie", orgLede: "Applicatienaam en hoe zaaknummers worden opgebouwd.", profile: "Profiel", profileLede: "Kies of deze werkruimte een zaaksysteem, een HR-systeem of beide is.", profileCases: "Zaakbehandeling", profileCasesHint: "Zaken, personen en bedrijven. Werknemers blijven systeemgebruikers.", profileHr: "HR", profileHrHint: "Medewerkergegevens, contracten en HR-documenten bijhouden.", profileBoth: "Zaken en HR", profileBothHint: "Zaakbehandeling plus een medewerkersregister.", personeelPrefix: "Prefix personeelsnummer", admin: "Beheerder", adminLede: "Dit account kan instellingen, gebruikers en integraties beheren.", create: "Create", createLede: "Koppel OmniDocs Create om documenten te maken. Je kunt dit overslaan en later onder Instellingen afmaken.", azure: "Microsoft Entra ID", azureLede: "Optioneel aanmelden met werkaccounts. Je kunt dit overslaan en later onder Instellingen afmaken.", next: "Doorgaan", skip: "Nu overslaan", finish: "Installatie afronden", back: "Terug", passwordConfirm: "Bevestig wachtwoord" },
    azure: { title: "Microsoft Entra ID", lede: "Laat medewerkers aanmelden met hun Microsoft-werkaccount.", tenantId: "Tenant-ID", clientId: "Toepassing (client)-ID", clientSecret: "Clientgeheim", keepSecret: "leeg laten om te behouden", redirectUri: "Omleidings-URI", redirectHint: "Registreer deze URI als webreactie in de Entra-appregistratie.", save: "Koppeling opslaan", clientConfigured: "App geregistreerd", clientMissing: "App ontbreekt" },
    dash: { title: "Dashboard", lede: "Overzicht van zaken, documenten en je NAW-register.", hrLede: "Overzicht van werknemers en documenten.", total: "Zaken totaal", open: "Open", progress: "In behandeling", closed: "Afgerond", split: "Verdeling op status", waiting: "Wachtend", overdue: "Doorlooptijd overschreden", noOverdue: "Geen verlopen zaken.", overdueBadge: "Verlopen", viewAll: "Alle zaken", recentCases: "Recente zaken", noCases: "Nog geen zaken.", recentDocs: "Recente documenten", noDocs: "Nog geen documenten geüpload.", board: "Bord", recentEmployees: "Recente werknemers", noEmployees: "Nog geen werknemers.", viewEmployees: "Alle werknemers" },
    status: { nieuw: "Nieuw", in_behandeling: "In behandeling", wacht_op_info: "Wacht op info", afgerond: "Afgerond", geannuleerd: "Geannuleerd" },
    priority: { laag: "Laag", normaal: "Normaal", hoog: "Hoog", urgent: "Urgent" },
    role: { admin: "Beheerder", zaakmanager: "Zaakmanager", medewerker: "Medewerker" },
    group: { open: "Open", progress: "In behandeling", closed: "Afgerond" },
    personGroup: { active: "Actief", anon: "Geanonimiseerd" },
    companyGroup: { linked: "Met zaken", idle: "Zonder zaken" },
    common: { save: "Opslaan", cancel: "Annuleren", edit: "Bewerken", delete: "Verwijderen", apply: "Toepassen", filter: "Filter", close: "Sluiten", none: "Geen.", back: "Terug naar overzicht", addFilter: "+ Filter toevoegen", grouped: "Gegroepeerde lijst", tableView: "Tabel", boardView: "Bord", days: "{n} dagen", connected: "Verbonden", notConfigured: "Niet geconfigureerd", download: "Download" },
    cases: { overview: "Zaakoverzicht", new: "Nieuwe zaak", edit: "Zaak bewerken", search: "Zoek titel, persoon, referentie", allStatuses: "Alle statussen", noFound: "Geen zaken gevonden.", noInStatus: "Geen zaken in deze status.", title: "Titel", caseId: "Zaaknummer", type: "Type", progress: "Voortgang", reference: "Referentie", name: "Naam", status: "Status", noDescription: "Geen omschrijving.", assignee: "Behandelaar", deadline: "Deadline", open: "Zaak openen", confirmDelete: "Deze zaak verwijderen?", dossier: "Dossier", created: "Aangemaakt", createdBy: "door {name}", updated: "Gewijzigd", links: "Koppelingen", companies: "Bedrijven", persons: "Personen", attachments: "Bijlagen", upload: "Uploaden", noAttachments: "Nog geen bijlagen. Bestanden staan op het data-volume.", createDoc: "Document maken", createOff: "Create is niet actief. Een beheerder kan dit aanzetten onder Instellingen → Integraties.", noTemplatesLinked: "Dit zaaktype heeft gekoppelde templates, maar die zijn nog niet gesynchroniseerd.", noTemplates: "Geen templates. Synchroniseer onder Templates of koppel ze aan het zaaktype.", pickTemplate: "Kies een template", openCreate: "Open in Create", createHint: "Zaakgegevens gaan mee als prefill. Create opent in dit tabblad.", description: "Omschrijving", progressPct: "Voortgang (%)", priority: "Prioriteit", generateDoc: "Document genereren", generateInteractive: "Interactief genereren", tabDetails: "Zaakgegevens", tabDocuments: "Documenten", leadTime: "Doorlooptijd", leadStart: "Startdatum doorlooptijd", plannedEnd: "Geplande einddatum", stakeholders: "Betrokkenen", more: "Meer", caseManager: "Zaakmanager", noStakeholders: "Geen betrokkenen gekoppeld.", confirmDeleteDoc: "Dit document verwijderen?", docUploaded: "Geüpload", docInCreate: "In Create", docCompleted: "Afgerond", docFailed: "Mislukt", docGenerating: "Bezig met genereren", leadHint: "Samen met het zaaktype (doorlooptijd) bepaalt dit de geplande einddatum.", stakeholderHint: "Voeg personen of bedrijven toe als betrokkenen.", searchStakeholder: "Zoek op naam of e-mail…", stakeholderPerson: "Persoon", stakeholderCompany: "Bedrijf", add: "Toevoegen", caseIdSoon: "Wordt bij opslaan toegekend", createPayload: "Bericht naar Create" },
    persons: { overview: "Personenoverzicht", new: "Nieuwe persoon", edit: "Persoon bewerken", search: "Zoek naam, e-mail, ID", all: "Alle personen", noFound: "Geen personen gevonden.", noInStatus: "Geen personen in deze status.", name: "Naam", personId: "Persoonsnummer", company: "Bedrijf", email: "E-mail", phone: "Telefoon", place: "Plaats", cases: "Zaken", noAddress: "Geen adres", open: "Persoon openen", firstName: "Voornaam", lastName: "Achternaam", dob: "Geboortedatum", bsn: "BSN", address: "Adres", postcode: "Postcode", keepBsn: "Leeg laten om te behouden", storedEnc: "Versleuteld opgeslagen", confirmAnon: "Gegevens anonimiseren? Zaakhistorie blijft behouden.", anonymise: "Anonimiseren", confirmDelete: "Persoon definitief verwijderen?", show: "tonen", hide: "verbergen", linkedCases: "Gekoppelde zaken", noCases: "Geen zaken.", anonymised: "Geanonimiseerd", eyebrow: "Persoon", infix: "Tussenvoegsel", gender: "Geslacht", male: "Man", female: "Vrouw", other: "Anders", street: "Straat", houseNo: "Huisnummer", country: "Land" },
    companies: { overview: "Bedrijvenoverzicht", new: "Nieuw bedrijf", edit: "Bedrijf bewerken", search: "Zoek naam, KvK, plaats", all: "Alle bedrijven", noFound: "Geen bedrijven gevonden.", noInStatus: "Geen bedrijven in deze status.", name: "Naam", companyId: "Bedrijfsnummer", place: "Plaats", cases: "Zaken", noAddress: "Geen adres", open: "Bedrijf openen", kvk: "KvK", phone: "Telefoon", email: "E-mail", address: "Adres", postcode: "Postcode", notes: "Notities", confirmDelete: "Dit bedrijf verwijderen?", linkedCases: "Gekoppelde zaken", noCases: "Geen zaken.", eyebrow: "Bedrijf" },
    employees: { overview: "Werknemersoverzicht", new: "Nieuwe werknemer", edit: "Werknemer bewerken", search: "Zoek naam, nummer of e-mail", allRoles: "Alle rollen", noInRole: "Geen werknemers in deze rol.", name: "Naam", email: "E-mail", role: "Rol", department: "Afdeling", open: "Werknemer openen", firstName: "Voornaam", lastName: "Achternaam", password: "Wachtwoord", keepPassword: "Leeg laten om te behouden", confirmDelete: "Deze werknemer verwijderen?", assignedCases: "Behandelde zaken", noCases: "Geen zaken.", eyebrow: "Werknemers" },
    hr: { tabContact: "Contactgegevens", contact: "Contactgegevens", employment: "Dienstverband", address: "Adres", staffNo: "Personeelsnummer", job: "Functiebenaming", location: "Vestiging", startDate: "Datum indiensttreding", updated: "Bijgewerkt", salutation: "Aanhef", heer: "De heer", mevrouw: "Mevrouw", dob: "Geboortedatum", scale: "Inschaling", salary: "Salaris", companyCar: "Leaseauto", yes: "Ja", no: "Nee", street: "Straat", houseNo: "Huisnummer", postcode: "Postcode", city: "Plaats", account: "Aanmelden", passwordHint: "Leeg laten als deze persoon niet moet inloggen." },
    audit: { overview: "Auditoverzicht", refresh: "Vernieuwen", search: "Zoek gebruiker, actie, entiteit", all: "Alle entiteiten", noEvents: "Geen gebeurtenissen in deze status.", time: "Tijd", user: "Gebruiker", action: "Actie", entity: "Entiteit", detail: "Detail" },
    entity: { zaak: "Zaken", persoon: "Personen", bedrijf: "Bedrijven", werknemer: "Werknemers", instellingen: "Instellingen", recipe: "Templates", document: "Documenten", zaaktype: "Zaaktypen" },
    settings: { title: "Instellingen", general: "Algemeen", generalHint: "Organisatienaam, profiel en nummering", caseTypes: "Zaaktypen", caseTypesHint: "Zaaktypen, doorlooptijd en templates", integrations: "Integraties", integrationsHint: "API, webhooks, unit en documentuitvoer", templates: "Templates", templatesHint: "Create-templates voor documenten", back: "‹ Terug naar instellingen", generalTitle: "Algemeen", generalLede: "Organisatienaam, applicatieprofiel en hoe nummers worden opgebouwd.", orgName: "Organisatienaam", prefix: "Zaaknummer-prefix", nextNumber: "Volgende nummer:", nextStaff: "Volgend personeelsnummer:", save: "Opslaan", demoTitle: "Voorbeelddata", demoLede: "Importeer voorbeeldpersonen en -bedrijven in het {lang}. Bestaande records blijven staan; eerder geïmporteerde items worden overgeslagen.", demoImport: "Voorbeelddata importeren", demoConfirm: "Voorbeeldpersonen en -bedrijven voor de huidige taal toevoegen?" },
    caseTypes: { title: "Zaaktypen", lede: "Naam, doorlooptijd en welke Create-templates bij een type horen.", new: "+ Nieuw zaaktype", empty: "Nog geen zaaktypen. Maak er een aan om zaken te categoriseren.", name: "Naam", leadTime: "Doorlooptijd", templates: "Templates", cases: "Zaken", edit: "Bewerken", newTitle: "Nieuw zaaktype", editTitle: "Zaaktype bewerken", formLede: "Doorlooptijd stelt een deadline voor bij een nieuwe zaak. Gekoppelde templates verschijnen bij documentgeneratie.", leadDays: "Doorlooptijd (dagen)", noTemplates: "Nog geen templates. Synchroniseer ze eerst onder", templatesHint: "Alleen aangevinkte templates worden aangeboden bij zaken van dit type. Niets aanvinken = alle templates.", search: "Templates zoeken", selectAll: "Alles selecteren", clear: "Wissen", confirmDelete: "Dit zaaktype verwijderen? Bestaande zaken blijven bestaan.", back: "‹ Terug naar zaaktypen", notFound: "Dit zaaktype bestaat niet." },
    integrations: { title: "Integraties", lede: "Overzicht van gekoppelde integraties. Gebruik Bewerken in het actiemenu om Create in te stellen. Zet Actief uit om tijdelijk te pauzeren.", saveActive: "Opslaan welke integraties actief zijn", integration: "Integratie", summary: "Samenvatting", active: "Actief", actions: "Acties", edit: "Bewerken", test: "Verbinding testen", sync: "Templates synchroniseren", back: "‹ Terug naar integraties" },
    create: { title: "Create", lede: "OAuth-clientgegevens, unit en content source voor OmniDocs Create.", baseUrl: "API-basis-URL", clientId: "Client-ID", clientSecret: "Client secret", keepSecret: "leeg laten om te behouden", unitId: "Unit-ID", contentSourceId: "Content source-ID", publicUrl: "Publieke basis-URL (webhooks)", webhookHint: "Webhooks werken alleen als Create Zaakhub kan bereiken. Lokaal leeg laten.", authDomain: "Auth-domein", authDomainHint: "Wordt als ?authDomain= toegevoegd wanneer Create opent.", save: "Koppeling opslaan", templates: "Templates ({n})", lastSync: "Laatste sync:", clientConfigured: "Client ingesteld", clientMissing: "Client ontbreekt" },
    templates: { title: "Templates", lede: "Recipes uit OmniDocs Create. Synchroniseer ze en gebruik ze op een zaak.", sync: "Templates synchroniseren", notConfigured: "Create is nog niet geconfigureerd. Vul client, unit en content source in onder Instellingen → Integraties.", search: "Templates zoeken", empty: "Nog geen templates. Sla de koppeling op en klik op Synchroniseren.", fields: "Velden", visibility: "Zichtbaarheid", hidden: "Verborgen", visible: "Zichtbaar", selected: "{n} geselecteerd", allAllowed: "Alles toegestaan" },
    error: { title: "Fout", notFound: "Niet gevonden", notFoundPage: "Deze pagina bestaat niet.", notFoundCase: "Deze zaak bestaat niet.", notFoundCompany: "Dit bedrijf bestaat niet.", notFoundPerson: "Deze persoon bestaat niet.", notFoundEmployee: "Deze werknemer bestaat niet.", forbidden: "Geen toegang", forbiddenMsg: "Je rol heeft geen rechten voor deze pagina.", server: "Er ging iets mis. Probeer het opnieuw of bekijk de containerlogs." },
    toast: { caseCreated: "Zaak aangemaakt", caseSaved: "Zaak opgeslagen", caseDeleted: "Zaak verwijderd", noFile: "Geen bestand gekozen", attachmentAdded: "Bijlage toegevoegd", attachmentDeleted: "Document verwijderd", pickTemplate: "Kies een template", createOff: "Create is niet actief of nog niet geconfigureerd", noFinalize: "Document voorbereid, maar Create gaf geen finalize-URL terug", documentGenerated: "Document gegenereerd", noFileUri: "Document gegenereerd, maar Create gaf geen fileUri terug", companySaved: "Bedrijf opgeslagen", companyDeleted: "Bedrijf verwijderd", personSaved: "Persoon opgeslagen", personAnon: "Gegevens geanonimiseerd", personDeleted: "Persoon verwijderd", employeeSaved: "Werknemer opgeslagen", employeeDeleted: "Werknemer verwijderd", cannotDeleteSelf: "Je kunt jezelf niet verwijderen", settingsSaved: "Instellingen opgeslagen", typeSaved: "Zaaktype opgeslagen", typeDeleted: "Zaaktype verwijderd", integrationsSaved: "Actieve integraties opgeslagen", createSaved: "Create-koppeling opgeslagen", azureSaved: "Microsoft Entra ID-koppeling opgeslagen", fillCreate: "Vul client, unit en content source in", testOk: "Verbinding OK · {n} templates gevonden", testFail: "Verbinding mislukt: {msg}", configureFirst: "Configureer eerst Create", synced: "{n} templates gesynchroniseerd", syncFail: "Synchroniseren mislukt: {msg}", demoImported: "{companies} bedrijven en {persons} personen toegevoegd.", demoAlready: "Voorbeelddata voor deze taal staat al in het register." },
    validation: { nameRequired: "Naam is verplicht.", passwordRequired: "Wachtwoord is verplicht voor een nieuwe werknemer.", passwordMismatch: "Wachtwoorden komen niet overeen.", passwordShort: "Gebruik minstens 8 tekens." },
  },
};

function parseLang(value) {
  const id = String(value || "").toLowerCase().slice(0, 2);
  return LANGS.some((l) => l.id === id) ? id : "en";
}

function lookup(dict, key) {
  return key.split(".").reduce((obj, part) => (obj && obj[part] != null ? obj[part] : undefined), dict);
}

function t(lang, key, vars = {}) {
  const value = lookup(catalogs[lang], key) ?? lookup(catalogs.en, key) ?? key;
  return String(value).replace(/\{(\w+)\}/g, (_, name) => (vars[name] != null ? String(vars[name]) : ""));
}

function makeT(lang) {
  return (key, vars) => t(lang, key, vars);
}

function setLangCookie(res, lang) {
  res.cookie("lang", parseLang(lang), {
    maxAge: 365 * 86400000,
    sameSite: "lax",
    httpOnly: false,
    path: "/",
  });
}

function i18nMiddleware(req, res, next) {
  const lang = parseLang(req.cookies?.lang);
  const translate = makeT(lang);
  req.lang = lang;
  req.t = translate;
  res.locals.t = translate;
  res.locals.lang = lang;
  res.locals.langMeta = LANGS.find((l) => l.id === lang);
  res.locals.langs = LANGS;
  res.locals.currentUrl = req.originalUrl || "/";
  next();
}

module.exports = { LANGS, parseLang, t, makeT, setLangCookie, i18nMiddleware };
